/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Backend.Validator;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Aaminah1
 */
public class RHBSignup extends javax.swing.JFrame {
    boolean idPresent = false;
    boolean lnPresent = false;
    boolean fnPresent = false;
    boolean emailPresent = false;
    boolean userPresent = false;
    boolean passPresent = false;
    String output = "";

    /**
     * Creates new form RHBSignup
     */
    public RHBSignup() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        titleLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        fnLabel = new javax.swing.JLabel();
        lnLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        gradeLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        fnTextField = new javax.swing.JTextField();
        lnTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        userTextField = new javax.swing.JTextField();
        passTextField = new javax.swing.JPasswordField();
        gradeSpinner = new javax.swing.JSpinner();
        dobSpinner = new com.github.lgooddatepicker.components.DatePicker();
        codeOfConductLabel = new javax.swing.JLabel();
        yesRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        ErrorTextArea = new javax.swing.JScrollPane();
        errorsTextArea = new javax.swing.JTextArea();
        signupButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel11.setFont(new java.awt.Font("Didot", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(191, 138, 108));
        kGradientPanel1.setkGradientFocus(674);
        kGradientPanel1.setkStartColor(new java.awt.Color(11, 37, 105));

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("RHB HIGHSCHOOL HELP PORTAL");
        titleLabel.setAutoscrolls(true);
        titleLabel.setFont(new java.awt.Font("Didot", 1, 30)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titleLabel.setToolTipText("");

        idLabel.setText("ID:");
        idLabel.setFont(new java.awt.Font("Didot", 1, 20)); // NOI18N
        idLabel.setForeground(new java.awt.Color(255, 255, 255));

        fnLabel.setText("First Name:");
        fnLabel.setFont(new java.awt.Font("Didot", 1, 20)); // NOI18N
        fnLabel.setForeground(new java.awt.Color(255, 255, 255));

        lnLabel.setText("Last Name:");
        lnLabel.setFont(new java.awt.Font("Didot", 1, 20)); // NOI18N
        lnLabel.setForeground(new java.awt.Color(255, 255, 255));

        emailLabel.setText("Email:");
        emailLabel.setFont(new java.awt.Font("Didot", 1, 20)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));

        userLabel.setText("Username:");
        userLabel.setFont(new java.awt.Font("Didot", 1, 20)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 255));

        passLabel.setText("Password:");
        passLabel.setFont(new java.awt.Font("Didot", 1, 20)); // NOI18N
        passLabel.setForeground(new java.awt.Color(255, 255, 255));

        dobLabel.setText("Date of Birth:");
        dobLabel.setFont(new java.awt.Font("Didot", 1, 20)); // NOI18N
        dobLabel.setForeground(new java.awt.Color(255, 255, 255));

        gradeLabel.setText("Grade:");
        gradeLabel.setFont(new java.awt.Font("Didot", 1, 20)); // NOI18N
        gradeLabel.setForeground(new java.awt.Color(255, 255, 255));

        idTextField.setFont(new java.awt.Font("Didot", 0, 14)); // NOI18N
        idTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idTextField.setText("Enter your ID...");
        idTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        idTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idTextFieldFocusLost(evt);
            }
        });
        idTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idTextFieldMouseClicked(evt);
            }
        });
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        idTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idTextFieldKeyReleased(evt);
            }
        });

        fnTextField.setFont(new java.awt.Font("Didot", 0, 14)); // NOI18N
        fnTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fnTextField.setText("Enter your first name...");
        fnTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        fnTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnTextFieldFocusLost(evt);
            }
        });
        fnTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fnTextFieldMouseClicked(evt);
            }
        });
        fnTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnTextFieldKeyReleased(evt);
            }
        });

        lnTextField.setFont(new java.awt.Font("Didot", 0, 14)); // NOI18N
        lnTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lnTextField.setText("Enter your last name...");
        lnTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        lnTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lnTextFieldFocusLost(evt);
            }
        });
        lnTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lnTextFieldMouseClicked(evt);
            }
        });
        lnTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnTextFieldKeyReleased(evt);
            }
        });

        emailTextField.setFont(new java.awt.Font("Didot", 0, 14)); // NOI18N
        emailTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailTextField.setText("Enter your email...");
        emailTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusLost(evt);
            }
        });
        emailTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailTextFieldMouseClicked(evt);
            }
        });
        emailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTextFieldKeyReleased(evt);
            }
        });

        userTextField.setFont(new java.awt.Font("Didot", 0, 14)); // NOI18N
        userTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userTextField.setText("Enter your username...");
        userTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        userTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                userTextFieldFocusLost(evt);
            }
        });
        userTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTextFieldMouseClicked(evt);
            }
        });

        passTextField.setFont(new java.awt.Font("Didot", 0, 14)); // NOI18N
        passTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passTextField.setText("jPasswordField1");
        passTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passTextFieldFocusLost(evt);
            }
        });
        passTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passTextFieldMouseClicked(evt);
            }
        });

        gradeSpinner.setModel(new javax.swing.SpinnerNumberModel(8, 8, 12, 1));
        gradeSpinner.setFont(new java.awt.Font("Didot", 0, 18)); // NOI18N

        dobSpinner.setFont(new java.awt.Font("Didot", 0, 13)); // NOI18N
        dobSpinner.setSettings(null);

        codeOfConductLabel.setText("Code of Conduct:");
        codeOfConductLabel.setFont(new java.awt.Font("Didot", 1, 20)); // NOI18N
        codeOfConductLabel.setForeground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(yesRadioButton);
        yesRadioButton.setText("Yes");
        yesRadioButton.setBorder(null);
        yesRadioButton.setFont(new java.awt.Font("Didot", 1, 18)); // NOI18N
        yesRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        yesRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yesRadioButtonMouseClicked(evt);
            }
        });

        buttonGroup1.add(noRadioButton);
        noRadioButton.setText("No");
        noRadioButton.setBorder(null);
        noRadioButton.setFont(new java.awt.Font("Didot", 1, 18)); // NOI18N
        noRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        noRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noRadioButtonMouseClicked(evt);
            }
        });

        errorsTextArea.setColumns(20);
        errorsTextArea.setEditable(false);
        errorsTextArea.setLineWrap(true);
        errorsTextArea.setRows(5);
        errorsTextArea.setBorder(null);
        errorsTextArea.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        errorsTextArea.setForeground(new java.awt.Color(255, 51, 0));
        ErrorTextArea.setViewportView(errorsTextArea);

        signupButton.setText("Signup");
        signupButton.setFont(new java.awt.Font("Didot", 1, 24)); // NOI18N
        signupButton.setForeground(new java.awt.Color(51, 51, 51));
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idLabel)
                                            .addComponent(fnLabel)
                                            .addComponent(passLabel)
                                            .addComponent(gradeLabel)
                                            .addComponent(dobLabel)
                                            .addComponent(userLabel)
                                            .addComponent(emailLabel)
                                            .addComponent(lnLabel))
                                        .addGap(55, 55, 55)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(dobSpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(passTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ErrorTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(68, 68, 68)
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                                        .addComponent(yesRadioButton)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(noRadioButton))
                                                    .addComponent(gradeSpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(codeOfConductLabel)))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(287, 287, 287)
                                .addComponent(signupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(41, 41, 41)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnLabel)
                    .addComponent(fnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnLabel)
                            .addComponent(lnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userLabel)
                            .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passLabel)
                            .addComponent(passTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ErrorTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLabel)
                    .addComponent(dobSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradeLabel)
                    .addComponent(gradeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeOfConductLabel)
                    .addComponent(yesRadioButton)
                    .addComponent(noRadioButton))
                .addGap(18, 18, 18)
                .addComponent(signupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextFieldKeyReleased
        // TODO add your handling code here:
        String email = emailTextField.getText();

        //presence check
        if (!Validator.validRHBEmail(email))
        {
            emailTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 3, true));
            errorsTextArea.setText("Not a RHB email");
        }
        else
        {
            errorsTextArea.setText("");
            emailTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        }
        
    }//GEN-LAST:event_emailTextFieldKeyReleased

    private void emailTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTextFieldMouseClicked
        // TODO add your handling code here:
        
        emailTextField.setText("");
    }//GEN-LAST:event_emailTextFieldMouseClicked

    private void emailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusLost
        // TODO add your handling code here:
        if (emailTextField.getText().equals(""))
        {
            errorsTextArea.setText("Email can't be null");
            signupButton.setEnabled(false);
        }
        else
        {
            signupButton.setEnabled(true);
            emailPresent = true;
        }
        
        
    }//GEN-LAST:event_emailTextFieldFocusLost

    private void lnTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnTextFieldKeyReleased
        // TODO add your handling code here:
        String lastname = lnTextField.getText();

        //presence check
        if (Validator.hasSpecialChar(lastname))
        {
            lnTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 3, true));
            errorsTextArea.setText("Can't have special characters/numbers");
        }
        else
        {
            errorsTextArea.setText("");
            lnTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        }
    }//GEN-LAST:event_lnTextFieldKeyReleased

    private void lnTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnTextFieldMouseClicked
        // TODO add your handling code here:
        lnTextField.setText("");
    }//GEN-LAST:event_lnTextFieldMouseClicked

    private void lnTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnTextFieldFocusLost
        // TODO add your handling code here:
        if (lnTextField.getText().equals(""))
        {
            errorsTextArea.setText("Last name can't be null");
            signupButton.setEnabled(false);
        }
        else
        {
            signupButton.setEnabled(true);
            lnPresent = true;
        }

    }//GEN-LAST:event_lnTextFieldFocusLost

    private void fnTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnTextFieldKeyReleased
        // TODO add your handling code here:
        String firstname = fnTextField.getText();

        //presence check
        if (Validator.hasSpecialChar(firstname))
        {
            fnTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 3, true));
            errorsTextArea.setText("Can't have special characters/numbers");
        }
        else
        {
            errorsTextArea.setText("");
            fnTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        }
    }//GEN-LAST:event_fnTextFieldKeyReleased

    private void fnTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fnTextFieldMouseClicked
        // TODO add your handling code here:
        fnTextField.setText("");
    }//GEN-LAST:event_fnTextFieldMouseClicked

    private void fnTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnTextFieldFocusLost
        // TODO add your handling code here:
        if (fnTextField.getText().equals(""))
        {
            errorsTextArea.setText("First name can't be null");
            signupButton.setEnabled(false);
        }
        else
        {
            signupButton.setEnabled(true);
            fnPresent = true;
        }
    }//GEN-LAST:event_fnTextFieldFocusLost

    
    private void idTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idTextFieldMouseClicked
        // TODO add your handling code here:
        idTextField.setText("");
    }//GEN-LAST:event_idTextFieldMouseClicked

    private void idTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTextFieldFocusLost
        //presence check
        if (idTextField.getText().equals(""))
        {
            errorsTextArea.setText("ID can't be null");
            signupButton.setEnabled(false);
        }
        else
        {
            signupButton.setEnabled(true);
            idPresent = true;
        }
        
    }//GEN-LAST:event_idTextFieldFocusLost

    private void idTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextFieldKeyReleased
        // TODO add your handling code here:
        String id = idTextField.getText();
        String output = "";

        //lookup table check
        if (!Validator.idExists(id))
        {
            idTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 3, true));
            output += "Doesn't exist in the RHB database\n";
        }
        else
        {
            errorsTextArea.setText("");
            idTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));

        }

        //length check
        if (!Validator.idLength(id))
        {
            output += "Incorrect length";
        }
        else
        {
            errorsTextArea.setText("");
        }

        //do logic check and presence check

        errorsTextArea.setText(output);
    }//GEN-LAST:event_idTextFieldKeyReleased

    private void userTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userTextFieldFocusLost
        // TODO add your handling code here:
        if (userTextField.getText().equals(""))
        {
            errorsTextArea.setText("Username can't be null");
            signupButton.setEnabled(false);
        }
        else
        {
            signupButton.setEnabled(true);
            userPresent = true;
        }
        
    }//GEN-LAST:event_userTextFieldFocusLost

    private void passTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTextFieldFocusLost
        // TODO add your handling code here:
        if (passTextField.getText().equals(""))
        {
            errorsTextArea.setText("Password can't be null");
            signupButton.setEnabled(false);
        }
        else
        {
            signupButton.setEnabled(true);
            passPresent = true;
        }
        
    }//GEN-LAST:event_passTextFieldFocusLost

    private void userTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTextFieldMouseClicked
        // TODO add your handling code here:
        userTextField.setText("");
    }//GEN-LAST:event_userTextFieldMouseClicked

    private void passTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTextFieldMouseClicked
        // TODO add your handling code here:
        passTextField.setText("");
    }//GEN-LAST:event_passTextFieldMouseClicked

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        // TODO add your handling code here:
        
        if (!(dobSpinner.getDate() == null))
        {
            LocalDate date = dobSpinner.getDate();
            DateTimeFormatter inputformat = DateTimeFormatter.ofPattern("yyMMdd");
            String DOB = date.format(inputformat);
            DateTimeFormatter outputFormatter = DateTimeFormatter.ofPattern("dd MMMM yyyy");
            
            if (!Validator.dobVerify(date, idTextField.getText()))
            {
                idTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 3, true));
                dobSpinner.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 3, true));
                errorsTextArea.setText("Date of birth doesn't match ID");
            }
            else
            {
                idTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
                dobSpinner.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
                errorsTextArea.setText("");

                if (idPresent & fnPresent & lnPresent & emailPresent & userPresent & passPresent)
                {
                    JOptionPane.showMessageDialog(null, "Success! All data has been validated", "Message", JOptionPane.INFORMATION_MESSAGE);
                    System.out.println("ID: " + idTextField.getText() +"\nFirst Name: " + fnTextField.getText() + "\nLast Name: " + lnTextField.getText() + "\nEmail: " + emailTextField.getText() + "\nUsername: " + userTextField.getText() + "\nPassword: " + passTextField.getText() +  "\nDate of Birth: " + date.format(outputFormatter) + "\nGrade: " + gradeSpinner.getValue());
                }
            }
        }
        else
        {
            errorsTextArea.setText("Date of Birth cannot be null");
        }
        
        


        
        
        
        
        
        
        
    }//GEN-LAST:event_signupButtonActionPerformed

    private void noRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noRadioButtonMouseClicked
        // TODO add your handling code here:
        
        
        errorsTextArea.setText("You have to agree to code of conduct");
        signupButton.setVisible(false);
       
        
            
    }//GEN-LAST:event_noRadioButtonMouseClicked

    private void yesRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yesRadioButtonMouseClicked
        // TODO add your handling code here:
        errorsTextArea.setText("");
        signupButton.setVisible(true);
    }//GEN-LAST:event_yesRadioButtonMouseClicked

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RHBSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RHBSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RHBSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RHBSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RHBSignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ErrorTextArea;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel codeOfConductLabel;
    private javax.swing.JLabel dobLabel;
    private com.github.lgooddatepicker.components.DatePicker dobSpinner;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextArea errorsTextArea;
    private javax.swing.JLabel fnLabel;
    private javax.swing.JTextField fnTextField;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JSpinner gradeSpinner;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lnLabel;
    private javax.swing.JTextField lnTextField;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passTextField;
    private javax.swing.JButton signupButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTextField;
    private javax.swing.JRadioButton yesRadioButton;
    // End of variables declaration//GEN-END:variables
}
